spring:
  config:
    import: "classpath:api.yml"
baidu:
  endpoint: https://fanyi-api.baidu.com/api/trans/vip/translate
  appid: ${api.baidu.appid}
  key: ${api.baidu.key}
fastapi:
  endpoint: http://localhost:8000/translate/en2zh
